// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Location struct {
	ID       int64  `json:"id"`
	Location string `json:"location"`
}

type LocationHistory struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	//
	//     1 - manual_input,
	//     2 - agent_location,
	//
	Type int32 `json:"type"`
	//
	//     = 0: user manual input,
	//     > 0: user scan code
	//     from agent location
	//
	LocationID  int32     `json:"location_id"`
	ManualInput string    `json:"manual_input"`
	Date        time.Time `json:"date"`
}

type User struct {
	ID               int64  `json:"id"`
	Name             string `json:"name"`
	PermanentAddress string `json:"permanent_address"`
	CurrentAddress   string `json:"current_address"`
	//
	//     -1: unknow,
	//     0: F0,
	//     1: F1,
	//     2: F2,
	//
	CurrentStatus int32 `json:"current_status"`
}
